# DLT Pipeline configuration for Kafka multi-client processing
resources:
  pipelines:
    kafka_client_pipeline:
      name: ${var.pipeline_name}
      catalog: ${var.catalog}
      target: ${var.schema}
      
      libraries:
        - notebook:
            path: ../src/kafka_dlt_pipeline.ipynb

      serverless: true
      continuous: true
      
      channel: PREVIEW

      configuration:
        kafka.bootstrap.servers: ${var.kafka_bootstrap_servers}
        kafka.topic: ${var.kafka_topic}
        # Note: kafka.consumer.group.id not supported on serverless
        alert.email: ${var.alert_email}
        catalog: ${var.catalog}
        base_schema: ${var.schema}
        # Enable expect failure logging
        pipelines.enableTraceInPython: "true"

      notifications:
        - email_recipients:
            - ${var.alert_email}
          alerts:
            - "on-update-failure"
            - "on-update-fatal-failure"
            - "on-flow-failure"

